/**
 * A unit generated by `npx audora generate`, opened in the viewer — docs/CLI.md, "Server and app".
 *
 * The CLI writes `.audora/local/units/<id>.json`, the server serves it at `/api/local/units/:id`,
 * and its assets sit under `/local-assets/<world_id>/…`. This module is the ONE place that file
 * becomes store records: a `Tour` whose `shareId` **is** the unit id (so `/t/<id>` finds it), one
 * `Room` per room in the file, and each room's world attached through exactly the path a Marble
 * world already takes — `worldFromMarble` then `attachWorld`. Nothing here is a second
 * implementation of anything the viewer does, which is why walk, photo, dollhouse, measure, layers,
 * the unit map and the portals all work on a local unit without knowing it is one.
 *
 * Conventions:
 * - **Copy, never re-derive.** The CLI already measured every room (`measureRoom` in
 *   server/pipeline.ts) and printed those numbers, so `raw`, `bounds`, `planDims` and `measurement`
 *   come off the file as they are — and so does the *scale*: the room's anchor is restated at the
 *   fused `measurement.scale` ({@link anchorForRoom}), and re-stated once more after the world is
 *   attached, because the store re-derives an anchor from a single source when a world arrives.
 *   The browser must show what the terminal showed, to the centimetre.
 * - **Deterministic ids.** The tour is found by `shareId === unit id`, and a room's store id is
 *   `room_<unit>_<room>` — so `/t/<unit>/<room>` is the same link for the same photos, before and
 *   after a re-import, which is the whole point of the CLI's determinism.
 * - **Idempotent.** {@link openLocalUnit} hashes the bytes it fetched and compares them with the
 *   hash the tour was imported at; an unchanged file touches the store not at all.
 * - **Pure underneath.** {@link rawForRoom}, {@link anchorForRoom} and {@link worldForRoom} are
 *   plain functions of the file; every store write is inside {@link importLocalUnit}.
 * - **Tolerant reader.** The file is written by another program on the same machine, so every field
 *   is validated and a missing one degrades (no world → a pending room; no plan → no unit map)
 *   rather than throwing the renter onto the not-found page.
 */
import { anchorFromCeiling, anchorFromFloorplan, anchorFromMarble } from '@/engine/anchor';
import { round } from '@/engine/geometry';
import type { AnchorSpec, DoorSpec, RawGeometry, RoomType, WindowSpec } from '@/engine/types';
import { fnv1a } from '@/lib/ids';
import { planRoomType } from '@/services/floorplan';
import type { PlanFloor, PlanRoom } from '@/services/floorplan';
import { rawFromBounds, worldFromMarble, type MarbleWorld } from '@/services/marble';
import { mockRawGeometry } from '@/services/mockWorld';
import { useAudora } from '@/state/store';
import type { PlanDimensions, Room, RoomWorld, Tier, TourFloorPlan, TourSite, WorldBoundsRecord } from '@/state/types';
import { orientPlan, type RoomMeasurement } from '@shared/fusion';

/* ------------------------------------------------------------------ the file on disk */

/** Our own copies of a world's assets, as URLs under `/local-assets/<world_id>/`. */
export interface LocalWorldAssets {
  /** Keyed the way Marble keys its ladder (`100k`, `500k`, `full_res`), so the splat streamer can climb it. */
  spz?: Record<string, string> | null;
  collider?: string | null;
  pano?: string | null;
  thumbnail?: string | null;
}

/** One room's finished world, as the CLI stored it (`LocalWorld` in server/local.ts). */
export interface LocalWorld {
  worldId?: string;
  provider?: string;
  tier?: string;
  model?: string;
  recipeHash?: string;
  seed?: number;
  /** The provider's own viewer link. `marbleUrl` is what the browser's record calls it. */
  worldUrl?: string;
  marbleUrl?: string;
  caption?: string;
  assets?: LocalWorldAssets | null;
  metricScaleFactor?: number | null;
  groundPlaneOffset?: number | null;
  bounds?: unknown;
  raw?: unknown;
  credits?: number | null;
  seconds?: number | null;
  /** ISO or epoch ms; the unit's own `createdAt` stands in when a world does not carry one. */
  createdAt?: string | number | null;
}

/** One room of the unit file. */
export interface LocalRoom {
  id: string;
  name?: string;
  type?: string;
  order?: number;
  recipeHash?: string;
  seed?: number;
  prompt?: string;
  model?: string;
  world?: LocalWorld | null;
  planDims?: Record<string, unknown> | null;
  measurement?: RoomMeasurement | null;
}

/** `.audora/local/units/<id>.json` — the shape docs/CLI.md prints. */
export interface LocalUnitFile {
  id: string;
  name?: string;
  createdAt?: string | number;
  address?: string;
  tier?: string;
  rooms: LocalRoom[];
  plan?: unknown;
  /** Optional: the geocoded site, when the CLI was given an `--address` it could resolve. */
  site?: unknown;
}

/** What opening a local unit did. */
export type LocalUnitOutcome = 'imported' | 'unchanged' | 'not-found';

/* ------------------------------------------------------------------ small readers */

const isRecord = (x: unknown): x is Record<string, unknown> => typeof x === 'object' && x !== null && !Array.isArray(x);

const num = (x: unknown): number | undefined => (typeof x === 'number' && Number.isFinite(x) ? x : undefined);

const str = (x: unknown): string | undefined => (typeof x === 'string' && x.trim() ? x.trim() : undefined);

/** Epoch ms from an ISO string or a number. Undefined for anything that is not a real instant. */
function timeOf(x: unknown): number | undefined {
  const n = num(x);
  if (n != null) return n;
  const s = str(x);
  if (!s) return undefined;
  const t = Date.parse(s);
  return Number.isFinite(t) ? t : undefined;
}

const ROOM_TYPES: ReadonlySet<string> = new Set<RoomType>(['living', 'bedroom', 'kitchen', 'dining', 'bathroom', 'office', 'hallway', 'studio', 'other']);

const roomTypeOf = (x: unknown): RoomType | undefined => (typeof x === 'string' && ROOM_TYPES.has(x) ? (x as RoomType) : undefined);

/**
 * The collider's bounds, when the file carries a real measurement of them. All six extents are
 * required: a half-written box would place the reconstruction somewhere it never was.
 */
export function boundsOf(x: unknown): WorldBoundsRecord | undefined {
  if (!isRecord(x)) return undefined;
  const minX = num(x.minX);
  const maxX = num(x.maxX);
  const minY = num(x.minY);
  const maxY = num(x.maxY);
  const minZ = num(x.minZ);
  const maxZ = num(x.maxZ);
  if (minX == null || maxX == null || minY == null || maxY == null || minZ == null || maxZ == null) return undefined;
  const walls = isRecord(x.walls) ? x.walls : undefined;
  return {
    minX,
    maxX,
    minY,
    maxY,
    minZ,
    maxZ,
    ...(num(x.floorY) != null ? { floorY: num(x.floorY) as number } : {}),
    ...(num(x.ceilingY) != null ? { ceilingY: num(x.ceilingY) as number } : {}),
    ...(x.method === 'walls' || x.method === 'aabb' ? { method: x.method } : {}),
    ...(walls ? { walls: walls as unknown as NonNullable<WorldBoundsRecord['walls']> } : {}),
  };
}

const doorOf = (x: unknown, fallbackWidth: number): DoorSpec => {
  const d = isRecord(x) ? x : {};
  const wall = d.wall === 'north' || d.wall === 'east' || d.wall === 'west' ? d.wall : 'south';
  return { wall, offset: num(d.offset) ?? fallbackWidth / 2, width: num(d.width) ?? fallbackWidth * 0.2, height: num(d.height) ?? 1 };
};

const windowsOf = (x: unknown): WindowSpec[] =>
  Array.isArray(x)
    ? x.filter(isRecord).map((w) => ({
        wall: w.wall === 'south' || w.wall === 'east' || w.wall === 'west' ? w.wall : 'north',
        offset: num(w.offset) ?? 0,
        width: num(w.width) ?? 0,
        height: num(w.height) ?? 0,
        sill: num(w.sill) ?? 0,
      }))
    : [];

/** The room's proportions in the provider's own units, when the file states them. */
export function rawOf(x: unknown): RawGeometry | undefined {
  if (!isRecord(x)) return undefined;
  const width = num(x.width);
  const depth = num(x.depth);
  const height = num(x.height);
  if (!(width && width > 0) || !(depth && depth > 0) || !(height && height > 0)) return undefined;
  return {
    width,
    depth,
    height,
    door: doorOf(x.door, width),
    windows: windowsOf(x.windows),
    // A reconstruction with no tapped door still needs the two reference heights an anchor divides
    // by; a standard door and outlet against the ceiling are what `unitsFromMetres` would give.
    doorHeightUnits: num(x.doorHeightUnits) ?? (height * 2.03) / 2.44,
    outletHeightUnits: num(x.outletHeightUnits) ?? (height * 0.3) / 2.44,
  };
}

/** What the unit's drawing printed for one room. */
export function planDimsOf(r: Pick<LocalRoom, 'planDims'>): PlanDimensions | undefined {
  const p = r.planDims;
  if (!isRecord(p)) return undefined;
  const width = num(p.width);
  const depth = num(p.depth);
  if (!(width && width > 0) && !(depth && depth > 0)) return undefined;
  return {
    width: width ?? 0,
    depth: depth ?? 0,
    ...(num(p.height) != null ? { height: num(p.height) as number } : {}),
    ...(str(p.text) ? { text: str(p.text) as string } : {}),
    ...(str(p.ceilingText) ? { ceilingText: str(p.ceilingText) as string } : {}),
    ...(str(p.planRoomName) ? { planRoomName: str(p.planRoomName) as string } : {}),
    ...(str(p.floor) ? { floor: str(p.floor) as string } : {}),
  };
}

/**
 * The unit's floor plan, when the file carries one with rooms on it — everything the unit map and
 * the portals need (`buildUnitGraph`, shared/unitGraph.ts). A plan with no floors is no plan.
 */
export function floorPlanOf(x: unknown): TourFloorPlan | undefined {
  if (!isRecord(x) || !Array.isArray(x.floors)) return undefined;
  const floors: PlanFloor[] = x.floors.filter(isRecord).map((f, i) => ({
    label: str(f.label) ?? `Floor ${i + 1}`,
    rooms: (Array.isArray(f.rooms) ? f.rooms.filter(isRecord) : []).map((r) => {
      const name = str(r.name) ?? 'Room';
      const room: PlanRoom = {
        name,
        type: roomTypeOf(r.type) ?? planRoomType(name),
        ...(num(r.width) != null ? { width: num(r.width) as number } : {}),
        ...(num(r.depth) != null ? { depth: num(r.depth) as number } : {}),
        ...(str(r.dimensionsText) ? { dimensionsText: str(r.dimensionsText) as string } : {}),
        ...(r.dimensionsFrom === 'text' || r.dimensionsFrom === 'model' ? { dimensionsFrom: r.dimensionsFrom } : {}),
        ...(num(r.height) != null ? { height: num(r.height) as number } : {}),
        ...(str(r.ceilingText) ? { ceilingText: str(r.ceilingText) as string } : {}),
        ...(num(r.windows) != null ? { windows: num(r.windows) as number } : {}),
        ...(num(r.doors) != null ? { doors: num(r.doors) as number } : {}),
      };
      return room;
    }),
  }));
  if (!floors.some((f) => f.rooms.length)) return undefined;
  const units = x.units === 'feet' || x.units === 'metres' || x.units === 'mixed' ? x.units : 'unknown';
  return {
    units,
    floors,
    northArrow: northArrowOf(x.northArrow),
    notes: Array.isArray(x.notes) ? x.notes.filter((n): n is string => typeof n === 'string') : [],
    source: x.source === 'nebius' ? 'nebius' : 'heuristic',
    ...(str(x.model) ? { model: str(x.model) as string } : {}),
    parsedAt: timeOf(x.parsedAt) ?? 0,
    ...(str(x.imageUrl) ? { imageUrl: str(x.imageUrl) as string } : {}),
    ...(str(x.fileName) ? { fileName: str(x.fileName) as string } : {}),
  };
}

/** Which way the drawing's north arrow points on the page. A plan without one simply has none. */
function northArrowOf(x: unknown): TourFloorPlan['northArrow'] {
  if (!isRecord(x)) return null;
  const d = x.direction;
  return {
    present: x.present !== false,
    ...(d === 'up' || d === 'right' || d === 'down' || d === 'left' ? { direction: d } : {}),
    ...(num(x.degrees) != null ? { degrees: num(x.degrees) as number } : {}),
  };
}

/** The geocoded site, when the CLI resolved an `--address`. Without lat/lon there is no sun to draw. */
export function siteOf(x: unknown): TourSite | undefined {
  if (!isRecord(x)) return undefined;
  const lat = num(x.lat);
  const lon = num(x.lon);
  if (lat == null || lon == null) return undefined;
  return {
    lat,
    lon,
    displayName: str(x.displayName) ?? '',
    heading: num(x.heading) ?? 0,
    ...(isRecord(x.footprint) ? { footprint: x.footprint as unknown as TourSite['footprint'] } : {}),
    ...(x.windowWall === 'north' || x.windowWall === 'south' || x.windowWall === 'east' || x.windowWall === 'west' ? { windowWall: x.windowWall } : {}),
    ...(timeOf(x.previewTime) != null ? { previewTime: timeOf(x.previewTime) as number } : {}),
    ...(timeOf(x.resolvedAt) != null ? { resolvedAt: timeOf(x.resolvedAt) as number } : {}),
  };
}

/**
 * The unit file, read out of whatever the server answered with.
 *
 * `id` is the id that was **asked for**, not the one the document claims: the URL the renter opened
 * is the contract, and a document whose own id disagrees with its file name is a bug in the writer
 * that must not silently move the tour onto a different share link. The mismatch is logged, because
 * a live run has to be diagnosable from the console.
 */
export function localUnitFrom(value: unknown, id: string): LocalUnitFile | undefined {
  if (!isRecord(value) || !Array.isArray(value.rooms)) return undefined;
  const claimed = str(value.id);
  if (claimed && claimed !== id) console.warn(`[audora] /api/local/units/${id} answered with unit ${claimed}; opening it as ${id}`);
  const rooms: LocalRoom[] = value.rooms.filter(isRecord).map((r, i) => ({
    id: str(r.id) ?? `room-${i + 1}`,
    ...(str(r.name) ? { name: str(r.name) as string } : {}),
    ...(str(r.type) ? { type: str(r.type) as string } : {}),
    order: num(r.order) ?? i,
    ...(str(r.recipeHash) ? { recipeHash: str(r.recipeHash) as string } : {}),
    ...(num(r.seed) != null ? { seed: num(r.seed) as number } : {}),
    ...(str(r.prompt) ? { prompt: str(r.prompt) as string } : {}),
    ...(str(r.model) ? { model: str(r.model) as string } : {}),
    ...(isRecord(r.world) ? { world: r.world as LocalWorld } : {}),
    ...(isRecord(r.planDims) ? { planDims: r.planDims } : {}),
    ...(isRecord(r.measurement) ? { measurement: r.measurement as unknown as RoomMeasurement } : {}),
  }));
  return {
    id,
    ...(str(value.name) ? { name: str(value.name) as string } : {}),
    ...(timeOf(value.createdAt) != null ? { createdAt: timeOf(value.createdAt) as number } : {}),
    ...(str(value.address) ? { address: str(value.address) as string } : {}),
    ...(str(value.tier) ? { tier: str(value.tier) as string } : {}),
    rooms,
    ...(value.plan != null ? { plan: value.plan } : {}),
    ...(value.site != null ? { site: value.site } : {}),
  };
}

/* ------------------------------------------------------------------ ids and the change test */

/** Only what a store id and a URL segment may contain; anything else in a folder name becomes a dash. */
const slug = (s: string): string => s.replace(/[^A-Za-z0-9_-]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 48) || 'x';

/**
 * A room's id in the store, derived from the unit and the room the file names rather than drawn at
 * random — so `/t/<unit>/<room>` survives a re-import and is the same link on every machine that
 * generated the same photos.
 */
export const localRoomId = (unitId: string, roomId: string): string => `room_${slug(unitId)}_${slug(roomId)}`;

/**
 * "Has the file changed?" — nothing more. A 32-bit hash of the bytes with their length beside it is
 * plenty for that question (a collision costs a skipped re-import, not a wrong render), and it is
 * synchronous, which `crypto.subtle` is not.
 */
export const contentHash = (text: string): string => `${text.length.toString(36)}-${fnv1a(text).toString(36)}`;

/** Where the server serves the unit file (docs/CLI.md). */
export const localUnitUrl = (id: string): string => `/api/local/units/${encodeURIComponent(id)}`;

/* ------------------------------------------------------------------ file → store records */

/**
 * The room's proportions in the world's own units: what the CLI measured, the rectangle it measured
 * them from, or — for a room with no reconstruction at all — a deterministic stand-in on its own id.
 */
export function rawForRoom(r: LocalRoom): RawGeometry {
  const raw = rawOf(r.world?.raw);
  if (raw) return raw;
  const bounds = boundsOf(r.world?.bounds);
  if (bounds) return rawFromBounds(bounds);
  return mockRawGeometry(`local:${r.id}`, roomTypeOf(r.type) ?? 'other');
}

/**
 * The room's anchor — the one declared reference every number in the UI is derived from — in the
 * order the file can supply it:
 *
 * 1. **The model's own metric scale** (`metric_scale_factor`, full quality only): the reconstruction
 *    measured itself, so the anchor quotes its ceiling.
 * 2. **The floor plan**, when the drawing printed this room's width and depth: ±5 cm, and the
 *    printed pair is oriented onto the measured rectangle first (`orientPlan`) — a wall fit's
 *    rotation is only defined modulo 90°, so pairing the plan as drawn would anchor a rotated room
 *    on its own depth. Only a printed *width* can anchor, because `anchorFromFloorplan` divides by
 *    the room's width; a drawing that printed depth alone falls through rather than lie about which
 *    wall it measured.
 * 3. **The assumed 2.44 m ceiling**, ±12 cm — coarse, free and always available.
 *
 * The store re-derives this against the world's own raw units the moment the world is attached
 * (`attachWorld`), which for each of the three branches is the same arithmetic on the same numbers.
 */
export function anchorForRoom(raw: RawGeometry, r: LocalRoom): AnchorSpec {
  const base = declaredAnchor(raw, r);
  const measured = num(r.measurement?.scale);
  // Only against the room the CLI actually measured: a scale in metres per raw unit means nothing
  // against the stand-in units of a room that has no reconstruction on this machine.
  const real = Boolean(rawOf(r.world?.raw) || boundsOf(r.world?.bounds));
  return measured != null && measured > 0 && real ? fusedAnchor(base, raw, r.measurement as RoomMeasurement, measured) : base;
}

/** The single source the file names, before the fusion weighed it against the others. */
function declaredAnchor(raw: RawGeometry, r: LocalRoom): AnchorSpec {
  const msf = num(r.world?.metricScaleFactor);
  if (msf != null && msf > 0) return anchorFromMarble(msf, raw.height);
  const plan = planDimsOf(r);
  if (plan) {
    const width = plan.width > 0 && plan.depth > 0 ? orientPlan(raw, { width: plan.width, depth: plan.depth }).width : plan.width;
    if (width > 0) return anchorFromFloorplan(raw, width);
  }
  return anchorFromCeiling(raw);
}

/**
 * The same anchor, restated at the scale the CLI actually fused and printed.
 *
 * The printed width, the printed depth, the stated ceiling and the model's own metric scale are
 * four claims about one number, and `shared/fusion.ts` weighs them into one (`measurement.scale`)
 * — which is the scale the terminal printed, the scale in `geometry` in the unit file, and the
 * scale the residuals below the room are quoted against. Anchoring on any single one of them
 * instead makes the viewer disagree with the terminal about how big the room is, and makes the
 * panel disagree with itself: a headline of "3.30 × 3.96 m" three lines above "plan says 3.30 m ·
 * model measures 3.51 m". So the anchor keeps the source's *name* (which is what the chip and the
 * ± are about) and takes the fused scale as its value.
 *
 * The reference is restated in the units the store re-derives that method from — width or depth for
 * a plan or a wall, the ceiling otherwise — so every later `setRaw`/`attachWorld` recomputes the
 * same metres per unit instead of drifting back to the single source.
 */
function fusedAnchor(base: AnchorSpec, raw: RawGeometry, m: RoomMeasurement, scale: number): AnchorSpec {
  const units =
    base.method === 'wall' || base.method === 'floorplan'
      ? base.axis === 'depth'
        ? raw.depth
        : raw.width
      : base.method === 'outlet'
        ? raw.outletHeightUnits
        : base.method === 'door' || base.method === 'assumed'
          ? raw.doorHeightUnits
          : raw.height;
  if (!(units > 0)) return base;
  const referenceMetres = round(units * scale, 3);
  // The fusion's own 1σ, on the reference this anchor quotes; never finer than the ±1 cm the chip
  // can print, and never so coarse it swallows the room.
  const uncertaintyM = Math.min(1, Math.max(0.01, round(referenceMetres * (num(m.sigmaRel) ?? 0), 2)));
  const what = base.method === 'wall' || base.method === 'floorplan' ? `${base.axis === 'depth' ? 'side wall' : 'far wall'} ${referenceMetres.toFixed(2)} m` : `ceiling ${referenceMetres.toFixed(2)} m`;
  const sources = num(m.independentSources) ?? m.residuals?.length ?? 0;
  return {
    ...base,
    referenceUnits: units,
    referenceMetres,
    metresPerUnit: scale,
    uncertaintyM,
    label: `measured · ${what} · ±${Math.max(1, Math.round(uncertaintyM * 100))} cm`,
    detail: `Every source this room has, fused into one scale${sources ? ` (${sources} independent)` : ''}. The plan-versus-model lines below say how far each one sits from it.`,
  };
}

/**
 * The room's world, through the same conversion a live Marble response goes through.
 *
 * The file's assets are re-assembled into the response shape `worldFromMarble` reads
 * (`assets.splats.spz_urls`, `mesh.collider_mesh_url`, `imagery.pano_url`, `thumbnail_url`,
 * `semantics_metadata`) so there is exactly one piece of code that decides what a world's fields
 * mean — the piece that already works against the live API. Only two things are then taken off the
 * file instead: the world's own creation time, and the measured room.
 *
 * `raw` and `bounds` are taken **as a pair or not at all**. The CLI measured this world once
 * (`measureRoom`, server/pipeline.ts) and the viewer sizes the room from one rectangle and centres
 * the capture on that same one (`splatTransform`); mixing the file's rectangle with a locally
 * re-derived room is the one way to get a reconstruction that stands in the wrong place.
 */
export function worldForRoom(room: Room, r: LocalRoom, unitTier: Tier, createdAt: number): RoomWorld | undefined {
  const w = r.world;
  const worldId = str(w?.worldId);
  if (!w || !worldId) return undefined;
  const a = w.assets ?? {};
  const spz = isRecord(a.spz) ? (a.spz as Record<string, string>) : undefined;
  const bounds = boundsOf(w.bounds);
  const tier: Tier = w.tier === 'full' || w.tier === 'draft' ? w.tier : unitTier;
  const marbleUrl = str(w.marbleUrl) ?? str(w.worldUrl);
  const response: MarbleWorld = {
    world_id: worldId,
    ...(str(w.model) ? { model: str(w.model) as string } : {}),
    ...(marbleUrl ? { world_marble_url: marbleUrl } : {}),
    assets: {
      ...(str(a.thumbnail) ? { thumbnail_url: str(a.thumbnail) as string } : {}),
      ...(str(w.caption) ? { caption: str(w.caption) as string } : {}),
      ...(str(a.pano) ? { imagery: { pano_url: str(a.pano) as string } } : {}),
      ...(str(a.collider) ? { mesh: { collider_mesh_url: str(a.collider) as string } } : {}),
      splats: {
        ...(spz ? { spz_urls: spz } : {}),
        semantics_metadata: { metric_scale_factor: num(w.metricScaleFactor) ?? null, ground_plane_offset: num(w.groundPlaneOffset) ?? null },
      },
    },
  };
  const recipeHash = str(w.recipeHash) ?? str(r.recipeHash);
  const seed = num(w.seed) ?? num(r.seed);
  const world = worldFromMarble(room, tier, response, num(w.credits), num(w.seconds), bounds, {
    ...(recipeHash ? { recipeHash } : {}),
    ...(seed != null ? { seed } : {}),
    ...(str(r.prompt) ? { prompt: str(r.prompt) as string } : {}),
    ...(str(r.model) ? { model: str(r.model) as string } : {}),
  });
  const raw = rawOf(w.raw);
  return {
    ...world,
    // `MARBLE_MOCK=1` writes real files from a simulated provider, and the chips must say so
    // rather than claim a capture that never happened.
    provider: w.provider === 'mock' ? 'mock' : 'marble',
    createdAt: timeOf(w.createdAt) ?? createdAt,
    ...(raw && bounds ? { raw, bounds } : {}),
  };
}

/** The provenance chip beside a room in the leasing team's own screens. */
const noteFor = (world: RoomWorld | undefined): string => (world ? `local · ${world.model}` : 'local');

/**
 * Forget that these ids were ever deleted.
 *
 * A room removed by an earlier import leaves a tombstone (`AudoraState.deleted`, seven days) that
 * the cross-tab merge honours by dropping the record again. Re-importing a unit whose room came
 * back would then lose that room in whichever tab wrote second, so the tombstone is lifted at the
 * moment the room is re-created.
 */
function forgetTombstones(ids: string[]): void {
  useAudora.setState((s) => {
    if (!ids.some((id) => s.deleted[id])) return {};
    const deleted = { ...s.deleted };
    for (const id of ids) delete deleted[id];
    return { deleted };
  });
}

/**
 * Put a unit file into the store and return the id of the tour it became.
 *
 * Runs on an empty store and on one that already holds this unit: rooms are addressed by their
 * deterministic ids, so a re-import updates them in place (their share links, and the renter's
 * position in a room they are standing in, survive), rooms the file no longer has are removed, and
 * the tour's `roomIds` is rewritten to exactly the file's own order.
 */
export function importLocalUnit(file: LocalUnitFile, hash: string): string {
  const unitId = file.id;
  const tier: Tier = file.tier === 'full' ? 'full' : 'draft';
  const createdAt = timeOf(file.createdAt) ?? Date.now();
  const title = file.name ?? unitId;
  const address = file.address ?? '';
  const plan = floorPlanOf(file.plan);
  const site = siteOf(file.site);

  const existing = Object.values(useAudora.getState().tours).find((t) => t.shareId === unitId);
  const tourId = existing?.id ?? useAudora.getState().createTour({ title, address, quality: tier }).id;
  useAudora.getState().updateTour(tourId, {
    shareId: unitId,
    title,
    address,
    quality: tier,
    // A local unit is opened by its link and nothing else; there is no unpublished state for it.
    published: true,
    publishedAt: createdAt,
    createdAt,
    localUnit: { id: unitId, hash },
    ...(plan ? { floorPlan: plan } : {}),
  });
  if (site) useAudora.getState().setSite(tourId, site);

  const ordered = [...file.rooms].sort((a, b) => (a.order ?? 0) - (b.order ?? 0));
  const ids = ordered.map((r) => localRoomId(unitId, r.id));
  forgetTombstones(ids);

  ordered.forEach((r, i) => {
    const id = ids[i];
    const raw = rawForRoom(r);
    const anchor = anchorForRoom(raw, r);
    const name = r.name ?? r.id;
    const type = roomTypeOf(r.type) ?? planRoomType(name);
    const planDims = planDimsOf(r);
    const current = useAudora.getState().rooms[id];
    if (current && current.tourId === tourId) {
      useAudora.getState().updateRoom(id, { name, type, planDims });
      // In this order: `setRaw` keeps the room's existing anchor method and re-derives its scale
      // against the new units, then the file's own anchor replaces it outright.
      useAudora.getState().setRaw(id, raw);
      useAudora.getState().setAnchor(id, anchor);
    } else {
      useAudora.getState().addRoom(tourId, { id, name, type, raw, anchor, planDims });
    }
    const world = worldForRoom(useAudora.getState().rooms[id], r, tier, createdAt);
    if (world) {
      useAudora.getState().attachWorld(id, world);
      /* `attachWorld` re-derives the anchor from whichever single source the arriving world offers
         — a world with its own metric scale replaces the anchor outright. That is right for a room
         the leasing team is building in the app, and wrong here: this room was already measured
         once, on this machine, and the terminal printed the answer. So the file's anchor is stated
         again, against whatever raw units the room ended up with. */
      const settled = useAudora.getState().rooms[id];
      if (settled) useAudora.getState().setAnchor(id, anchorForRoom(settled.raw, r));
    }
    useAudora.getState().updateRoom(id, { order: r.order ?? i, measurement: r.measurement ?? undefined, note: noteFor(world) });
  });

  for (const id of useAudora.getState().tours[tourId]?.roomIds ?? []) if (!ids.includes(id)) useAudora.getState().removeRoom(id);
  useAudora.getState().updateTour(tourId, { roomIds: ids });
  return tourId;
}

/* ------------------------------------------------------------------ the network side */

/** Fetch and validate one unit file. `null` is "this machine has no such unit", which is not an error. */
export async function fetchLocalUnit(id: string, signal?: AbortSignal): Promise<{ file: LocalUnitFile; hash: string } | null> {
  const r = await fetch(localUnitUrl(id), { ...(signal ? { signal } : {}), headers: { accept: 'application/json' } });
  if (r.status === 404) return null;
  if (!r.ok) throw new Error(`${localUnitUrl(id)} answered ${r.status}`);
  const text = await r.text();
  let parsed: unknown;
  try {
    parsed = JSON.parse(text);
  } catch {
    throw new Error(`${localUnitUrl(id)} did not answer with JSON`);
  }
  const file = localUnitFrom(parsed, id);
  if (!file) throw new Error(`${localUnitUrl(id)} answered without a rooms list`);
  return { file, hash: contentHash(text) };
}

/**
 * Open `/t/<id>` against the units this machine has generated: fetch the file, and import it only
 * when it is not already in the store byte for byte.
 *
 * Safe to call on every open of a local unit — which is the point, because that is what makes the
 * link show a regenerated unit without ever re-importing an unchanged one.
 */
export async function openLocalUnit(id: string, signal?: AbortSignal): Promise<LocalUnitOutcome> {
  const got = await fetchLocalUnit(id, signal);
  if (!got) return 'not-found';
  const tour = Object.values(useAudora.getState().tours).find((t) => t.shareId === got.file.id);
  if (tour?.localUnit?.hash === got.hash) return 'unchanged';
  importLocalUnit(got.file, got.hash);
  return 'imported';
}
