/// <reference types="node" />
/**
 * One prompt compiler, one copy of it.
 *
 * `server/prompt.ts` renders the prompt for the pipeline and `src/services/marblePrompt.ts` renders
 * it for the browser flow, and the two must produce the same string for the same facts — a room
 * generated from the wizard and the same room generated by the backend describe themselves in the
 * same words, so the only thing that separates their recipes is the photo canonicalisation the
 * backend adds.
 *
 * That used to be a copy in each file, byte-compared here. It is now `shared/marblePrompt.ts`,
 * which both builds compile (docs/ACCURACY.md section 3), so the two sides agree because they hold
 * the *same function object* — which is what this test asserts, along with the thing that could
 * still go wrong: someone re-declaring the renderer on one side and quietly forking it again.
 *
 * The rest of the file is the browser's own half of the contract: `roomPromptFacts` maps a `Room`
 * from the store onto the facts the renderer takes, and nothing else in the app does that.
 */
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { compileMarblePrompt as compileShared, PROMPT_CONSTRAINTS as SHARED_CONSTRAINTS, PROMPT_MAX_CHARS as SHARED_MAX, type PromptFacts } from '../shared/marblePrompt';
import { compileMarblePrompt as compileServer, PROMPT_CONSTRAINTS as SERVER_CONSTRAINTS, PROMPT_MAX_CHARS as SERVER_MAX } from '../server/prompt';
import {
  compileMarblePrompt as compileBrowser,
  compileRoomPrompt,
  PROMPT_CONSTRAINTS as BROWSER_CONSTRAINTS,
  PROMPT_MAX_CHARS as BROWSER_MAX,
  roomPromptFacts,
} from '../src/services/marblePrompt';
import type { PhotoRecord, Room } from '../src/state/types';
import type { AnchorSpec, RawGeometry } from '../src/engine/types';
import { applyScale } from '../src/engine/anchor';

/** The constraints sentence every prompt ends with. */
const CONSTRAINTS = SHARED_CONSTRAINTS;

function source(file: string): string {
  return readFileSync(path.resolve(process.cwd(), file), 'utf8');
}

/** Every shape the renderer can take, including the two that hit the character cap. */
function battery(): PromptFacts[] {
  const long = (n: number) => Array.from({ length: n }, (_, i) => `listing note number ${i} about this room and its condition`);
  return [
    { roomType: 'kitchen', imageCount: 1 },
    { roomType: 'bedroom', imageCount: 2, empty: true, capturedFrom: 'doorway' },
    { roomType: 'living', imageCount: 3, empty: false, capturedFrom: 'corner', widthM: 3.75, depthM: 4.6, ceilingHeightM: 2.44 },
    { roomType: 'other', imageCount: 1, widthM: 2.4384, depthM: 3.048, doors: [{ wall: 'west', offset: -0.001 }] },
    {
      roomType: 'office',
      imageCount: 4,
      doors: [{ wall: 'south', offset: 1.2, width: 0.9, height: 2.03, swing: 'inward' }],
      windows: [
        { wall: 'north', offset: 0.9, width: 1.4, height: 1.2, sill: 0.9 },
        { wall: 'east', offset: 2, width: 0.8, height: 1.2, sill: 0.9 },
      ],
    },
    {
      roomType: 'studio',
      imageCount: 6,
      photoCaption: 'White walls, oak boards and a radiator under the window',
      flooring: 'oak',
      walls: 'white',
      trim: 'white',
      fixtures: ['radiator under the window', 'pendant light'],
      notes: ['renovated 2021'],
    },
    { roomType: 'hallway', imageCount: 1, floorLevel: 0, buildingType: 'brick apartment building', buildingYear: 1925, city: 'Boston', windowFacing: 261.4, captureHour: 15 },
    { roomType: 'dining', imageCount: 2, floorLevel: -1, buildingYear: 1880, windowFacing: -90, captureHour: 23 },
    // Invalid values everywhere: the renderer must omit exactly these things.
    {
      roomType: 'bathroom',
      imageCount: 2,
      widthM: 3.5,
      ceilingHeightM: -1,
      doors: [],
      windows: [{ wall: 'up' as never, offset: 1 }],
      flooring: '   ',
      photoCaption: '  ',
      fixtures: ['', '  \n '],
      floorLevel: 2.5,
      buildingYear: 12,
      city: '...',
      windowFacing: NaN,
      captureHour: 24,
    },
    // Over the cap: context goes first, then finishes, then openings.
    { roomType: 'living', imageCount: 2, widthM: 4, depthM: 5, notes: long(4), fixtures: long(6), city: 'Boston', floorLevel: 2, windowFacing: 180, captureHour: 9, doors: [{ width: 0.9, height: 2.03 }] },
    { roomType: 'living', imageCount: 2, widthM: 4, depthM: 5, notes: long(4), fixtures: long(6), photoCaption: long(1)[0], windows: Array.from({ length: 8 }, () => ({ width: 1.4, height: 1.2, sill: 0.9 })) },
  ];
}

describe('the prompt compiler', () => {
  it('is one function, imported by both sides', () => {
    // Not "the same output": the same object. Nothing can drift between two names for one binding.
    expect(compileServer).toBe(compileShared);
    expect(compileBrowser).toBe(compileShared);
    expect(SERVER_CONSTRAINTS).toBe(SHARED_CONSTRAINTS);
    expect(BROWSER_CONSTRAINTS).toBe(SHARED_CONSTRAINTS);
    expect(SERVER_MAX).toBe(SHARED_MAX);
    expect(BROWSER_MAX).toBe(SHARED_MAX);
  });

  it('is declared in shared/ and nowhere else', () => {
    // A re-export cannot fork; a second declaration can, which is how the copy started last time.
    expect(source('shared/marblePrompt.ts')).toMatch(/export function compileMarblePrompt\(/);
    for (const file of ['server/prompt.ts', 'src/services/marblePrompt.ts']) {
      expect(source(file), `${file} must re-export the compiler, not re-declare it`).not.toMatch(/function compileMarblePrompt\(/);
    }
  });

  it('renders every shape of facts, ending with the constraints', () => {
    for (const facts of battery()) {
      const text = compileShared(facts);
      expect(compileServer(facts), JSON.stringify(facts)).toBe(text);
      expect(compileBrowser(facts), JSON.stringify(facts)).toBe(text);
      expect(text.endsWith(CONSTRAINTS), `${text} must end with the constraints`).toBe(true);
      expect(text.length).toBeLessThanOrEqual(SHARED_MAX);
    }
  });

  it('rejects nonsense', () => {
    for (const bad of [0, -1, 1.5, Number.NaN]) {
      expect(() => compileShared({ roomType: 'other', imageCount: bad })).toThrow(RangeError);
    }
  });
});

/* ---------- and the browser's Room mapper feeds that same renderer ---------- */

const RAW: RawGeometry = { width: 4, depth: 5, height: 2.6, door: { wall: 'south' as const, offset: 1, width: 0.9, height: 2.1 }, windows: [], doorHeightUnits: 2.1, outletHeightUnits: 0.3 };
const DOOR_ANCHOR: AnchorSpec = { method: 'door', referenceMetres: 2.03, referenceUnits: 2.1, metresPerUnit: 2.03 / 2.1, uncertaintyM: 0.04, label: 'interior door' };

function photo(bytes: string, angle?: PhotoRecord['angle']): PhotoRecord {
  return { dataUrl: `data:image/jpeg;base64,${Buffer.from(bytes).toString('base64')}`, width: 1600, height: 1200, brightness: 0.5, darkFraction: 0.1, detail: 0.2, ...(angle ? { angle } : {}) };
}

function room(over: Partial<Room> = {}): Room {
  return {
    id: 'room_a',
    tourId: 'tour_a',
    name: 'Bedroom',
    type: 'bedroom',
    order: 0,
    photo: photo('photo-a'),
    raw: RAW,
    anchor: DOOR_ANCHOR,
    geometry: applyScale(RAW, DOOR_ANCHOR.metresPerUnit),
    staging: [],
    stagingStyle: 'minimal',
    status: 'pending',
    createdAt: 1,
    updatedAt: 1,
    ...over,
  };
}

describe('roomPromptFacts', () => {
  it('compiles a room through the shared renderer to exactly what compileRoomPrompt returns', () => {
    const r = room({
      planDims: { width: 3.75, depth: 4.2 },
      northWallHeading: 264.4,
      photos: [photo('b', 'left'), photo('c')],
      analysis: { roomType: 'bedroom', roomTypeConfidence: 0.9, isEmpty: true, doorVisible: true, quality: 'good', notes: ['radiator under the window'], caption: 'White walls and an oak floor.  ', source: 'nebius' },
    });
    const facts = roomPromptFacts(r);
    expect(compileShared(facts)).toBe(compileRoomPrompt(r));
    expect(compileRoomPrompt(r)).toBe(
      '3 photographs of one real, empty bedroom, taken from the doorway. ' +
        'The room measures 3.8 m by 4.2 m (12 ft 4 in by 13 ft 9 in) on the floor plan. ' +
        '1 door, 2.0 m high. ' +
        'As photographed: White walls and an oak floor. Listing notes: radiator under the window. ' +
        'The windows face west. ' +
        CONSTRAINTS,
    );
  });

  it('states nothing the room does not know: no ceiling height, no assumed emptiness', () => {
    const bare = compileRoomPrompt(room());
    expect(bare).toBe(`1 photograph of one real bedroom, taken from the doorway. 1 door, 2.0 m high. ${CONSTRAINTS}`);
    // the constraints sentence mentions the ceiling; a stated HEIGHT is what must never appear.
    expect(bare).not.toMatch(/Ceiling height/);
    // A wall anchor is not a door, and the heuristic caption is a placeholder, not a description.
    const wall = compileRoomPrompt(
      room({
        anchor: { ...DOOR_ANCHOR, method: 'wall', referenceMetres: 4.2, axis: 'depth' },
        analysis: { roomType: 'bedroom', roomTypeConfidence: 0.5, isEmpty: false, doorVisible: false, quality: 'ok', notes: [], caption: 'An empty room.', source: 'heuristic' },
      }),
    );
    expect(wall).toBe(`1 photograph of one real, furnished bedroom, taken from the doorway. ${CONSTRAINTS}`);
  });

  it('counts exactly the photographs Marble is sent and prefers the room heading over the site', () => {
    const many = room({ photos: ['a', 'b', 'c', 'd', 'e', 'f'].map((s) => photo(s)) });
    expect(roomPromptFacts(many).imageCount).toBe(6);
    expect(compileRoomPrompt(many).startsWith('6 photographs of')).toBe(true);
    expect(roomPromptFacts(room({ northWallHeading: 90 }), { heading: 264.4 }).windowFacing).toBe(90);
    expect(roomPromptFacts(room(), { heading: 264.4 }).windowFacing).toBe(264.4);
    expect(roomPromptFacts(room()).windowFacing).toBeUndefined();
  });
});
